import { useMemo } from "react";
import { X } from "lucide-react";
import type { OrgNode } from "@/contexts/AppContext";
import { cn } from "@/lib/utils";
import type { ValidationErrors } from "@/features/user-management/types";
import {
  getBranchAppearance,
  getNodeAccentBorderLeft,
} from "@/features/org-structure/nodeTheme.utils";
import { formatCollapsedNodePath } from "@/features/user-management/utils";

type StepSelectNodeProps = {
  orgStructure: OrgNode | null;
  selectedNodeId: string | null;
  selectedNodes: OrgNode[];
  autoGeneratedNodeIds: string[];
  errors: ValidationErrors;
  onNodeSelect: (nodeId: string) => void;
  onRemoveNode: (nodeId: string) => void;
};

type BranchMeta = {
  branchIndex: number | null;
  branchDepth: number;
};

const buildNodeBreadcrumbMap = (root: OrgNode | null) => {
  const map = new Map<string, string>();
  if (!root) return map;

  const nodeLabel = (node: OrgNode) => {
    const name = typeof node.name === "string" ? node.name.trim() : "";
    if (name) return name;
    const type = typeof node.nodeType === "string" ? node.nodeType.trim() : "";
    return type || "Unnamed Node";
  };

  const walk = (node: OrgNode, trail: string[]) => {
    const nextTrail = [...trail, nodeLabel(node)].filter(Boolean);
    map.set(node.id, nextTrail.join(" > "));
    node.children.forEach((child) => walk(child, nextTrail));
  };

  walk(root, []);
  return map;
};

const isPendingNode = (node: OrgNode) => node.status?.trim().toUpperCase() === "PENDING";

const filterPendingNodes = (node: OrgNode | null): OrgNode | null => {
  if (!node || isPendingNode(node)) return null;

  return {
    ...node,
    children: node.children.map((child) => filterPendingNodes(child)).filter((child): child is OrgNode => Boolean(child)),
  };
};

const getNodeBorderLeftClass = (branchIndex: number | null, branchDepth: number, isRoot: boolean) =>
  isRoot ? "border-l-indigo-500" : getNodeAccentBorderLeft(branchIndex, branchDepth, isRoot);

const getSelectedNodeClass = (
  isRoot: boolean,
  isSelected: boolean,
  appearance: ReturnType<typeof getBranchAppearance>,
  branchIndex: number | null,
  branchDepth: number,
) => {
  const borderLeftClass = getNodeBorderLeftClass(branchIndex, branchDepth, isRoot);

  return isSelected
    ? isRoot
      ? "border border-indigo-200 bg-indigo-50/70 text-slate-800 shadow-[0_10px_22px_rgba(99,102,241,0.16)] border-l-[4px] border-l-indigo-400"
      : cn(
        "border-[rgb(53,83,233)] shadow-[0_0_0_3px_rgba(53,83,233,0.08)] bg-[rgb(53,83,233,0.02)] border-l-[4px]",
        borderLeftClass,
      )
    : cn(
      isRoot ? "border border-indigo-100 bg-indigo-50/35 text-slate-800 shadow-[0_6px_16px_rgba(99,102,241,0.1)]" : appearance.defaultSurfaceClass,
      appearance.hoverBorderClass,
      "border-l-[4px]",
      borderLeftClass,
    );
};

function buildBranchMetaMap(root: OrgNode | null): Map<string, BranchMeta> {
  const branchMap = new Map<string, BranchMeta>();
  if (!root) return branchMap;

  const walk = (node: OrgNode, branchIndex: number | null, branchDepth: number) => {
    branchMap.set(node.id, { branchIndex, branchDepth });

    const isRootNode = node.nodeType.trim().toUpperCase() === "ROOT";
    node.children.forEach((child, childIdx) => {
      const nextBranchIndex = isRootNode ? childIdx : (branchIndex ?? 0);
      const nextBranchDepth = isRootNode ? 0 : branchDepth + 1;
      walk(child, nextBranchIndex, nextBranchDepth);
    });
  };

  const isRootNode = root.nodeType.trim().toUpperCase() === "ROOT";
  walk(root, isRootNode ? null : 0, 0);
  return branchMap;
}

type FlowNode = {
  node: OrgNode;
  branchIndex: number | null;
  branchDepth: number;
  depth: number;
};

const getFlowNodes = (root: OrgNode | null, branchMetaMap: Map<string, BranchMeta>): FlowNode[] => {
  if (!root) return [];

  const linearNodes: Array<{ node: OrgNode; depth: number }> = [];
  const walk = (node: OrgNode, depth: number) => {
    linearNodes.push({ node, depth });
    node.children.forEach((child) => walk(child, depth + 1));
  };
  walk(root, 0);

  return linearNodes.map(({ node, depth }, index) => {
    const meta = branchMetaMap.get(node.id) ?? { branchIndex: null, branchDepth: 0 };

    return {
      node,
      branchIndex: meta.branchIndex,
      branchDepth: meta.branchDepth,
      depth,
    };
  });
};

export function UserOnboardingStepSelectNode({
  orgStructure,
  selectedNodeId,
  selectedNodes,
  autoGeneratedNodeIds,
  errors,
  onNodeSelect,
  onRemoveNode,
}: StepSelectNodeProps) {
  const filteredStructure = useMemo(() => filterPendingNodes(orgStructure), [orgStructure]);
  const branchMetaMap = useMemo(() => buildBranchMetaMap(filteredStructure), [filteredStructure]);
  const breadcrumbByNodeId = useMemo(() => buildNodeBreadcrumbMap(filteredStructure), [filteredStructure]);
  const selectedNodeIds = useMemo(() => new Set(selectedNodes.map((node) => node.id)), [selectedNodes]);
  const autoGeneratedNodeIdSet = useMemo(() => new Set(autoGeneratedNodeIds), [autoGeneratedNodeIds]);

  const flowNodes = useMemo(() => getFlowNodes(filteredStructure, branchMetaMap), [branchMetaMap, filteredStructure]);

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-300">
      {errors.nodeSelection ? (
        <div className="rounded-lg border border-destructive/30 bg-destructive/5 px-3 py-2 text-sm text-destructive">
          {errors.nodeSelection}
        </div>
      ) : null}

      <div className="grid grid-cols-1 gap-5 lg:grid-cols-[minmax(0,1.35fr)_minmax(18rem,0.8fr)]">
        <div className="rounded-2xl border border-slate-200 bg-slate-50/40 p-5">
          <div className="mb-4">
            <h3 className="text-base font-semibold text-slate-800">Select Node</h3>
            <p className="mt-1 text-xs text-slate-500">Click node rows to toggle selection.</p>
          </div>

          {flowNodes.length > 0 ? (
            <div className="max-h-[31rem] overflow-auto rounded-xl border border-slate-200 bg-white/80">
              <div className="space-y-2 p-3">
                {flowNodes.map((item) => {
                  const isRoot = item.node.nodeType.trim().toUpperCase() === "ROOT";
                  const isSelected = selectedNodeIds.has(item.node.id);
                  const isFocusedSelection = selectedNodeId === item.node.id;
                  const appearance = getBranchAppearance(item.branchIndex, item.branchDepth, isRoot);
                  const borderLeftClass = getNodeBorderLeftClass(item.branchIndex, item.branchDepth, isRoot);
                  const parentSubtitle = formatCollapsedNodePath(breadcrumbByNodeId.get(item.node.id) || "");

                  return (
                    <div key={item.node.id} style={{ paddingLeft: `${item.depth * 20}px` }}>
                      <button
                        type="button"
                        onClick={() => onNodeSelect(item.node.id)}
                        className={cn(
                          "group relative w-full overflow-hidden rounded-xl border bg-white px-3 py-2.5 text-left transition",
                          "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30",
                          getSelectedNodeClass(isRoot, isSelected, appearance, item.branchIndex, item.branchDepth),
                          isFocusedSelection && "ring-2 ring-[rgb(53,83,233)]/25 ring-offset-1",
                        )}
                      >
                        <span
                          className={cn(
                            "absolute left-0 top-0 h-full w-[4px] rounded-r-full",
                            isRoot ? "bg-indigo-400" : borderLeftClass,
                          )}
                          aria-hidden="true"
                        />
                        <div className="mb-2 flex items-center justify-between">
                          <div className="flex items-center gap-2.5">
                            {!isRoot ? (
                              <span className="text-[11px] font-bold uppercase tracking-[0.14em] text-slate-500">{item.node.nodeType}</span>
                            ) : null}
                          </div>
                          <span className={cn("text-xs font-semibold", isRoot ? "text-slate-500" : "text-slate-400")}>{isSelected ? "Selected" : "Select"}</span>
                        </div>
                        <div className={cn("flex items-center gap-2 rounded-xl border px-3 py-2", isRoot ? "border-indigo-200 bg-indigo-50/40" : "border-slate-200 bg-white")}>
                          <div className="min-w-0 flex-1">
                            <div className={cn("truncate text-[13px] font-semibold", isRoot ? "text-slate-800" : "text-slate-800")}>{item.node.name}</div>
                            {!isRoot ? (
                              <div className={cn("truncate text-[10px]", "text-slate-500")}>
                                {parentSubtitle || item.node.nodeType}
                              </div>
                            ) : null}
                          </div>
                        </div>
                      </button>
                    </div>
                  );
                })}
              </div>
            </div>
          ) : (
            <div className="rounded-xl border border-dashed border-slate-200 bg-white px-4 py-8 text-center text-sm text-slate-500">
              Org structure is not available yet.
            </div>
          )}
        </div>

        <div className="rounded-2xl border border-slate-200 bg-white p-5">
          <h4 className="text-sm font-bold uppercase tracking-[0.18em] text-slate-500">Selected Node</h4>
          <div className="mt-4 min-h-[22rem] space-y-3">
            {selectedNodes.length > 0 ? (
              selectedNodes.map((node, index) => (
                (() => {
                  const isRoot = node.nodeType.trim().toUpperCase() === "ROOT";
                  const meta = branchMetaMap.get(node.id) ?? { branchIndex: null, branchDepth: 0 };
                  const appearance = getBranchAppearance(meta.branchIndex, meta.branchDepth, isRoot);
                  const borderLeftClass = getNodeBorderLeftClass(meta.branchIndex, meta.branchDepth, isRoot);
                  const collapsedPath = formatCollapsedNodePath(breadcrumbByNodeId.get(node.id) || "");
                  const isAutoGenerated = autoGeneratedNodeIdSet.has(node.id);

                  return (
                    <div
                      key={node.id}
                      className={cn(
                        "relative flex items-start gap-3 overflow-hidden rounded-xl border border-l-[4px] bg-white px-4 py-3",
                        isRoot
                          ? "border border-indigo-100 bg-indigo-50/35 shadow-[0_6px_16px_rgba(99,102,241,0.1)]"
                          : appearance.defaultSurfaceClass,
                        borderLeftClass,
                      )}
                    >
                      <div className="min-w-0">
                        <div className="flex min-w-0 flex-wrap items-center gap-2">
                          <div className={cn("truncate text-[16px] font-semibold", isRoot ? "text-slate-800" : "text-slate-800")}>{node.name}</div>
                          {isAutoGenerated ? (
                            <span className="shrink-0 rounded-full border border-emerald-200 bg-emerald-50 px-2 py-0.5 text-[10px] font-black uppercase tracking-wider text-emerald-700">
                              Auto Generated
                            </span>
                          ) : null}
                        </div>
                        {!isRoot && collapsedPath ? (
                          <div className={cn("truncate text-[10px] font-medium", "text-slate-500")}>
                            {collapsedPath}
                          </div>
                        ) : null}
                        {!isRoot ? (
                          <div className="mt-0.5 text-[10px] uppercase tracking-[0.1em] text-slate-500">{node.nodeType}</div>
                        ) : null}
                      </div>
                      <button
                        type="button"
                        onClick={() => onRemoveNode(node.id)}
                        className={cn(
                          "ml-auto inline-flex h-7 w-7 shrink-0 items-center justify-center rounded-full transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30",
                          isRoot
                            ? "text-slate-500 hover:bg-indigo-100 hover:text-slate-700"
                            : "text-slate-400 hover:bg-slate-100 hover:text-slate-600",
                        )}
                        aria-label={`Remove ${node.name}`}
                      >
                        <X className="h-4 w-4" />
                      </button>
                    </div>
                  );
                })()
              ))
            ) : (
              <div className="rounded-xl border border-dashed border-slate-200 bg-slate-50/60 px-4 py-8 text-center text-sm text-slate-500">
                Selected nodes will appear here in preference order.
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

export default UserOnboardingStepSelectNode;
