export type WorkflowStatus = "Active" | "Pending" | "Inactive";

export type WorkflowOrgStructure = {
  nodePath: string;
  nodeName: string;
  nodeType: string;
  levelCount?: number;
};

export type WorkflowRecord = {
  id: string;
  referenceId?: string;
  workflowId?: string;
  levelsHash?: string;
  levelCount?: number;
  name: string;
  alias: string;
  isPending?: boolean;
  module: string;
  rawModule?: string;
  workflowType?: string;
  nodeName: string;
  nodeType: string;
  subModule: string;
  nodePath: string;
  orgStructure?: WorkflowOrgStructure | null;
  autoGenerated?: Array<{ orgStructure: WorkflowOrgStructure }>;
  linkedOrgStructure?: WorkflowOrgStructure[];
  levels: unknown;
  approvalRemark?: string;
  initiatorName?: string;
  initiatorEmail?: string;
  initiatedDate?: string;
  workflowName?: string;
  workflowAlias?: string;
  pendingRequestType?: string;
  pendingRequestImpact?: string;
  pendingOldData?: Record<string, unknown>;
  pendingNewData?: Record<string, unknown>;
  status: WorkflowStatus;
};

export const WORKFLOW_PAGE_SIZE_OPTIONS = [15, 25, 35, 50] as const;
export type WorkflowPageSize = (typeof WORKFLOW_PAGE_SIZE_OPTIONS)[number];
