import type { WorkflowRecord, WorkflowStatus } from "@/features/workflow-management/types/workflow.types";

type RawWorkflowRecord = Record<string, unknown>;

const readString = (value: unknown) => (typeof value === "string" ? value.trim() : "");
const toRecord = (value: unknown): RawWorkflowRecord =>
  typeof value === "object" && value !== null ? (value as RawWorkflowRecord) : {};

export const isWorkflowUpdateRequest = (input: { pendingRequestType?: string; pendingRequestImpact?: string }) => {
  const requestType = readString(input.pendingRequestType).toUpperCase();
  const requestImpact = readString(input.pendingRequestImpact).toUpperCase();
  return requestType === "UPDATE" || requestImpact === "WORKFLOW_UPDATE";
};

export const isRootWorkflowNode = (nodePath: string, nodeType?: string) => {
  if ((nodeType || "").trim().toUpperCase() === "ROOT") return true;
  const trimmed = nodePath.trim();
  if (!trimmed) return false;
  return !trimmed.includes(".");
};

const getNodeLabelFromPath = (nodePath: string) => {
  const segments = nodePath.split(".").map((segment) => segment.trim()).filter(Boolean);
  const last = segments[segments.length - 1] || "";
  return formatSnakeCaseLabel(last);
};

export const formatSnakeCaseLabel = (value: string) =>
  value
    .trim()
    .replace(/_/g, " ")
    .toLowerCase()
    .replace(/\b\w/g, (char) => char.toUpperCase());

export const formatWorkflowPath = (nodePath: string) =>
  nodePath
    .split(".")
    .map((segment) => segment.trim())
    .filter((segment) => Boolean(segment) && segment.toUpperCase() !== "ROOT")
    .map((segment) => formatSnakeCaseLabel(segment))
    .join(" > ");

const toNodePathSegmentLabel = (segment: string) => segment.trim().replace(/_/g, " ");

const splitNodePathSegments = (value: string) => {
  const trimmed = value.trim();
  if (!trimmed) return [];

  const rawParts = trimmed.includes(">")
    ? trimmed.split(">")
    : trimmed.split(".");

  return rawParts
    .map((part) => toNodePathSegmentLabel(part))
    .filter((part) => Boolean(part) && part.toUpperCase() !== "ROOT");
};

const normalizeOrgStructure = (value: unknown) => {
  const record = toRecord(value);
  const nodePath = readString(record.nodePath);
  const nodeName = readString(record.nodeName);
  const nodeType = readString(record.nodeType);
  if (!nodePath && !nodeName && !nodeType) return null;
  return { nodePath, nodeName, nodeType };
};

const normalizeLinkedOrgStructure = (value: unknown) => {
  const rows = Array.isArray(value) ? value : [];
  return rows
    .map((entry) => normalizeOrgStructure(entry))
    .filter((entry): entry is { nodePath: string; nodeName: string; nodeType: string } => Boolean(entry?.nodePath && entry?.nodeName));
};

const normalizeAutoGenerated = (value: unknown) => {
  const rows = Array.isArray(value) ? value : [];
  const parsed = rows
    .map((entry) => {
      const entryRecord = toRecord(entry);
      const fromNested = normalizeOrgStructure(entryRecord.orgStructure);
      const fromSelf = normalizeOrgStructure(entryRecord);
      const orgStructure = fromNested || fromSelf;
      if (!orgStructure?.nodePath || !orgStructure.nodeName) return null;
      return { orgStructure };
    })
    .filter((entry): entry is { orgStructure: { nodePath: string; nodeName: string; nodeType: string } } => Boolean(entry));
  return parsed;
};

const deriveModuleFromWorkflowName = (value: string) => {
  const normalized = value.trim().toUpperCase();
  if (!normalized) return "";

  const match = normalized.match(/^(.*?)_WORKFLOW(?:_|$)/);
  if (!match?.[1]) return "";
  return match[1].trim();
};

export const getWorkflowPathPreview = (nodePath: string, keepLast = 3) => {
  const segments = splitNodePathSegments(nodePath);
  if (segments.length === 0) return "";

  const root = segments[0] ?? "";
  const tail = segments.slice(1);
  if (tail.length <= keepLast) {
    return [root, ...tail].filter(Boolean).join(" > ");
  }

  return [root, "...", ...tail.slice(-keepLast)].filter(Boolean).join(" > ");
};

export const getWorkflowParentPathPreview = (nodePath: string) => {
  const segments = nodePath
    .split(".")
    .map((segment) => segment.trim())
    .filter((segment) => Boolean(segment) && segment.toUpperCase() !== "ROOT");

  if (segments.length <= 1) return "";

  const parentSegment = segments[segments.length - 2];
  return parentSegment ? formatSnakeCaseLabel(parentSegment) : "";
};

export const mapWorkflowRecord = (item: unknown, status: WorkflowStatus): WorkflowRecord => {
  const record = toRecord(item);
  const payload = toRecord(record.data);
  const associateAlias = toRecord(record.associateAlias);
  const payloadAssociateAlias = toRecord(payload.associateAlias);
  const pendingRequest = toRecord(record.pendingRequest);
  const pendingOldDataFromPending = toRecord(pendingRequest.oldData);
  const pendingNewDataFromPending = toRecord(pendingRequest.newData);
  const pendingOldDataFromRecord = toRecord(record.oldData);
  const pendingNewDataFromRecord = toRecord(record.newData);
  const pendingOldData =
    Object.keys(pendingOldDataFromPending).length > 0 ? pendingOldDataFromPending : pendingOldDataFromRecord;
  const pendingNewData =
    Object.keys(pendingNewDataFromPending).length > 0 ? pendingNewDataFromPending : pendingNewDataFromRecord;
  const orgStructure = toRecord(record.orgStructure);
  const initiator = toRecord(record.initiator);
  const topLevelWorkflowName =
    readString(record.workflowName) ||
    readString(payload.workflowName);
  const associatedWorkflowName =
    readString(associateAlias.workflowName) ||
    readString(payloadAssociateAlias.workflowName);
  const resolvedWorkflowName = topLevelWorkflowName || associatedWorkflowName;
  const inferredModule = deriveModuleFromWorkflowName(associatedWorkflowName || resolvedWorkflowName);
  const rawModule = readString(record.module) || readString(payload.module) || inferredModule;
  const subModule = readString(record.subModule) || readString(payload.subModule) || inferredModule;
  const nodePath =
    readString(record.nodePath) ||
    readString(orgStructure.nodePath) ||
    readString(payload.nodePath) ||
    readString(pendingNewData.nodePath);

  const id =
    readString(record.id) ||
    readString(record.referenceId) ||
    readString(record.workflowId) ||
    readString(record.requestId) ||
    readString(payload.referenceId) ||
    [
      readString(record.levelsHash) || readString(payload.levelsHash),
      rawModule || "module",
      subModule || "sub-module",
      nodePath || "node-path",
      readString(record.name) || readString(payload.name) || "workflow",
      status,
    ]
      .filter(Boolean)
      .join("|");
  const levelsHash =
    readString(record.levelsHash) ||
    readString(payload.levelsHash) ||
    readString(record.workflowId) ||
    readString(payload.workflowId);
  const workflowId =
    readString(record.workflowId) ||
    readString(payload.workflowId) ||
    id;
  const name =
    readString(record.name) ||
    readString(payload.name) ||
    readString(record.workflowName) ||
    readString(payload.workflowName) ||
    "-";
  const alias = readString(record.alias) || readString(payload.alias) || "-";
  const moduleName = readString(record.module) || readString(payload.module) || inferredModule || "-";
  const moduleDisplayName = subModule ? formatSnakeCaseLabel(subModule) : formatSnakeCaseLabel(moduleName);
  const workflowType = readString(record.workflowType) || readString(payload.workflowType);
  const isPending = Boolean(record.isPending ?? payload.isPending);
  const nodeType = readString(record.nodeType) || readString(orgStructure.nodeType) || readString(payload.nodeType);
  const nodeName =
    readString(record.nodeName) ||
    readString(orgStructure.nodeName) ||
    readString(record.department) ||
    (nodePath ? getNodeLabelFromPath(nodePath) : subModule || "-");
  const levels = record.levels ?? payload.levels ?? [];
  const normalizedOrgStructure =
    normalizeOrgStructure(record.orgStructure) ||
    normalizeOrgStructure(payload.orgStructure) ||
    (nodePath || nodeName || nodeType ? { nodePath, nodeName, nodeType } : null);
  const autoGenerated = normalizeAutoGenerated(record.autoGenerated ?? payload.autoGenerated);
  const linkedOrgStructure = normalizeLinkedOrgStructure(record.linkedOrgStructure ?? payload.linkedOrgStructure);

  return {
    id,
    referenceId:
      readString(record.referenceId) ||
      readString(record.requestId) ||
      readString(payload.referenceId),
    workflowId,
    levelsHash,
    name,
    alias,
    isPending,
    module: moduleDisplayName,
    rawModule,
    workflowType: workflowType || undefined,
    nodeName,
    nodeType: nodeType ? formatSnakeCaseLabel(nodeType) : "-",
    subModule,
    nodePath,
    orgStructure: normalizedOrgStructure,
    autoGenerated,
    linkedOrgStructure,
    levels,
    approvalRemark: readString(record.approvalRemark),
    initiatorName:
      readString(record.initiatorName) ||
      readString(payload.initiatorName) ||
      readString(initiator.name),
    initiatorEmail:
      readString(record.initiatorEmail) ||
      readString(payload.initiatorEmail) ||
      readString(initiator.email),
    initiatedDate:
      readString(record.initiatedDate) ||
      readString(record.initiatedAt) ||
      readString(record.initiatorTimestamp) ||
      readString(payload.initiatedDate) ||
      readString(payload.initiatedAt) ||
      readString(payload.initiatorTimestamp),
    workflowName:
      resolvedWorkflowName,
    workflowAlias:
      readString(associateAlias.workflowAlias) ||
      readString(payloadAssociateAlias.workflowAlias) ||
      readString(record.workflowAlias) ||
      readString(payload.workflowAlias) ||
      readString(record.alias) ||
      readString(payload.alias),
    pendingRequestType: readString(pendingRequest.type) || readString(record.type) || readString(payload.type),
    pendingRequestImpact: readString(pendingRequest.impact) || readString(record.impact) || readString(payload.impact),
    pendingOldData,
    pendingNewData,
    status,
  };
};
